version: '3.9'

services:
  mfplb:
    image: nginx:latest
    volumes:
      - ./src:/var/www/html
      - ./conf/dev/default.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.mfp.rule=Host(`mfp.localhost`)
    networks:
      - traefik
    depends_on:
      - mfpfpm

  mfpfpm:
    build: .
    volumes:
      - ./src:/var/www/html
    networks:
      - traefik

networks:
  traefik:
    external: true
